import keyboard
import pyautogui
import time
time.sleep(5)
pyautogui.moveTo(511, 28)
time.sleep(3)
pyautogui.click(button = 'right')
time.sleep(3)
pyautogui.moveTo(569, 205)
time.sleep(3)
pyautogui.moveTo(880, 344)
time.sleep(3)
pyautogui.doubleClick()
time.sleep(3)
pyautogui.press('enter')
time.sleep(3)
keyboard.write("Пиши здесь все что хочешь , точнее информацию котору.ты хочешь знать")
time.sleep(20)
pyautogui.keyDown('ctrl')
pyautogui.press('c')
time.sleep(2)
pyautogui.keyUp('ctrl')
time.sleep(2)
pyautogui.moveTo(33, 683)
pyautogui.doubleClick()
time.sleep(5)
pyautogui.hotkey('ctrl', 'v')
time.sleep(5)
pyautogui.press('enter')